server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Si el archivo pedido no existe (ej: /productos), devuelve index.html
        # y deja que React Router decida que mostrar
        try_files $uri $uri/ /index.html;
    }
}
